const { messageRandomizer } = require('../util/index')

const Messenger = require('../models/Messenger')

const selectMessage = (messageName) => ({
      'Welcome Text': Messenger.getWelcomeText()
    , 'Welcome Again Text': Messenger.getWelcomeAgainText()
    , 'Fallback First Interaction Text': Messenger.getFallbackFirstInteractionText()
    , 'Fallback Second Interaction Text': Messenger.getFallbackSecondInteractionText()
    , 'Prevention & Contagion Fallback First Interaction Text': Messenger.getPreventionNContagionFallbackFirstInteractionText()
    , 'Prevention & Contagion Fallback Second Interaction Text': Messenger.getPreventionNContagionFallbackSecondInteractionText()
    , 'Risk Groups Fallback First Interaction Text': Messenger.getRiskGroupsFallbackFirstInteractionText()
    , 'Risk Groups Fallback Second Interaction Text': Messenger.getRiskGroupsFallbackSecondInteractionText()
    , 'Risk Groups Fallback Second Interaction Quick Replies': Messenger.getRiskGroupsFallbackSecondInteractionQuickReplies()
    , 'Fever Fallback First Interaction Text': Messenger.getFeverFallbackFirstInteractionText()
    , 'Fever Fallback First Interaction Quick Replies': Messenger.getFeverFallbackFirstInteractionQuickReplies()
    , 'Fever Fallback Second Interaction Text': Messenger.getFeverFallbackSecondInteractionText()
    , 'Mild Symptoms Fallback First Interaction Text': Messenger.getMildSymptomsFallbackFirstInteractionText()
    , 'Mild Symptoms Fallback Second Interaction Text': Messenger.getMildSymptomsFallbackSecondInteractionText()
    , 'Mild Symptoms Fallback First Interaction Quick Replies': Messenger.getMildSymptomsFallbackSecondInteractionQuickReplies()
    , 'Drugs Taken Fallback First Interaction Text': Messenger.getDrugsTakenFallbackFirstInteractionText()
    , 'Drugs Taken Fallback First Interaction Quick Replies': Messenger.getDrugsTakenFallbackFirstInteractionQuickReplies()
    , 'Drugs Taken Fallback Second Interaction Text': Messenger.getDrugsTakenFallbackSecondInteractionText()
    , 'Drugs Taken Fallback Second Interaction Quick Replies': Messenger.getDrugsTakenFallbackSecondInteractionQuickReplies()
    , 'Got Well Fallback First Interaction Text': Messenger.getGotWellFallbackFirstInteractionText()
    , 'Got Well Fallback First Interaction Quick Replies': Messenger.getGotWellFallbackFirstInteractionQuickReplies()
    , 'Got Well Fallback Second Interaction Text': Messenger.getGotWellFallbackSecondInteractionText()
    , 'Got Well Fallback Second Interaction Quick Replies': Messenger.getGotWellFallbackSecondInteractionQuickReplies()
    , 'Severe Symptoms Fallback First Interaction Text': Messenger.getSevereSymptomsFallbackFirstInteractionText()
    , 'Severe Symptoms Fallback First Interaction Quick Replies': Messenger.getSevereSymptomsFallbackFirstInteractionQuickReplies()
    , 'Severe Symptoms Fallback Second Interaction Quick Replies': Messenger.getSevereSymptomsFallbackSecondInteractionQuickReplies()
    , 'Farewell Text': Messenger.getFarewellText()
    , 'Fallback Farewell Text': Messenger.getFallbackFarewellText()
    , 'Prevention N Contagion Fallback Farewell Text': Messenger.getPreventionNContagionFallbackFarewellText()
    , 'Pre Diagnostic Fallback Farewell Text': Messenger.getPreDiagnosticFallbackFarewellText()
    , 'Main Menu Quick Replies': Messenger.getMainMenuQuickReplies()
    , 'Main Menu Quick Replies Titles': messageRandomized(Messenger.getMainMenuQuickRepliesTitles())
    , 'First Main Menu Quick Replies Titles': messageRandomized(Messenger.getFirstMainMenuQuickRepliesTitles())
    , 'Prevention Text': Messenger.getPreventionText()
    , 'Prevention Quick Replies': Messenger.getPreventionQuickReplies()
    , 'Basic Prevention Text': Messenger.getBasicPreventionText()
    , 'Basic Prevention Quick Replies': Messenger.getBasicPreventionQuickReplies()
    , 'Health Professional Prevent Text': Messenger.getHealthProfessionalPreventionText()
    , 'Contagion Text': Messenger.getContagionText()
    , 'Contagion Quick Replies':  Messenger.getContagionQuickReplies()
    , 'Contagion Forms Text': Messenger.getContagionFormsText()
    , 'Incubation Period Text': Messenger.getIncubationPeriodText()
    , 'Pre Diagnostic Text': Messenger.getPreDiagnosticText()
    , 'Pre Diagnostic Quick Replies': Messenger.getPreDiagnosticQuickReplies()
    , 'Abort Pre Diagnostic Text': Messenger.getAbortPreDiagnosticText()
    , 'Risk Groups Text': Messenger.getRiskGroupsText()
    , 'Risk Groups Quick Replies': Messenger.getRiskGroupsQuickReplies()
    , 'Risk Groups Response Text': Messenger.getRiskGroupsResponseText()
    , 'Fever Quick Replies': Messenger.getFeverQuickReplies()
    , 'Mild Symptoms Text': Messenger.getMildSymptomsText()
    , 'Mild Symptoms Quick Replies': Messenger.getMildSymptomsQuickReplies()
    , 'Mild Symptoms Number Text': Messenger.getMildSymptomsNumberText()
    , 'Drugs Taken Quick Replies': Messenger.getDrugsTakenQuickReplies()
    , 'Got Well Quick Replies': Messenger.getGotWellQuickReplies()
    , 'No Mild Symptoms Text': Messenger.getNoMildSymptomsText()
    , 'Severe Symptoms Text': Messenger.getSevereSymptomsText()
    , 'Severe Symptoms Quick Replies': Messenger.getSevereSymptomsQuickReplies()
    , 'Need More Help Quick Replies': Messenger.getNeedMoreHelpQuickReplies()
}[messageName] || 'Menssagem não encontrada.')

const messageRandomized = (messages) => {
    return messageRandomizer(messages, messages.length)
}

module.exports = {
    selectMessage
}